# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            marcino239
tagline:          The blog
url:              http://marcino239.github.io
paginate:         1
baseurl:          /
author:
  name:           original by Mark Otto
  url:            
  email:         

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/marcino239/marcino239.github.io
